### ISSUE TITLE
CFP advice

### ISSUE THREAD

**Issue by krmaxwell** [krmaxwell/krmaxwell.github.io#10]
- If your approach is to submit to a CFP, then do the research if accepted, you're doing it completely backwards. Stop that.
- Thoughts on overcommitting
- Talks I'd like to see (not give)

**Comment by sroberts** [comment]
Not a bad place to point to speaking.io, which is pretty much the single thing that's leveled up my game. I think @mattjay also had a big post on writing better CFP responses.

**Comment by krmaxwell** [comment]
I have a list of blog posts to reference and White Hat has, like, two of them. Good call on http://speaking.io too.

**Comment by sroberts** [comment]
- http://www.inc.com/jill-krasny/github-zach-holman-speaking-tips.html
- http://zachholman.com/posts/what-they-dont-tell-you-about-public-speaking/
- http://zachholman.com/talk/the-talk-on-talks/

**Comment by krmaxwell** [comment]
> If your approach is to submit to a CFP, then do the research if accepted, you're doing it completely backwards. Stop that. The proper thing to do is start a bunch of research, then when it's decently well along, start submitting it. To be fair, it also depends on the _type_ of talk. a survey or tutorial is different than true research.

-- from my tweets

**Comment by krmaxwell** [comment]
- [4 Tips to Get a Conference "Call for Papers" Submission Accepted](http://blog.whitehatsec.com/4-tips-to-get-a-conference-call-for-papers-submission-accepted/) (Jeremiah Grossman)
- [How do I make my CFP stand out?](https://www.defcon.org/html/links/dc-speakerscorner.html#nikita-cfp) (Nikita)
- [Create Good Security CFP Responses](http://hexsec.blogspot.com/2012/12/create-good-security-cfp-responses.html) (Nathan Hamiel)
