### ISSUE TITLE
Intro to FIR

### ISSUE THREAD

**Issue by krmaxwell** [krmaxwell/krmaxwell.github.io#46]
https://github.com/certsocietegenerale/FIR

**Comment by krmaxwell** [comment]
possibly part of #52

**Comment by sroberts** [comment]
:+1: to see this.

**Comment by krmaxwell** [comment]
I haven't touched this in so long that it's probably not useful now.

**Comment by sroberts** [comment]
I don't agree actually. I think it could still be really useful.

**Comment by krmaxwell** [comment]
It would be useful if somebody else wrote it, sure. I have no idea about anything to do with FIR these days.
