### ISSUE TITLE
Economics of co-working

### ISSUE THREAD

**Issue by krmaxwell** [krmaxwell/krmaxwell.github.io#79]

**Comment by sroberts** [comment]
Really curious to see where you're going with this.

**Comment by krmaxwell** [comment]
general thought: if you're paying (say) $200/month or $25/day (the facility I'm looking at), then the delta in your productivity versus your current arrangement needs to make up for that. 

So if you're making $100k (purely for nice round numbers) and working there 20 days a month, then you're spending $10/day versus an hourly "rate" of $50/hr... easy to justify if you're literally getting 12 more minutes of productivity per day. Or even if you're doing the $25 day pass - if you get an extra 30 minutes...

This doesn't take into account any sort of commute time, though, so there's a bit more, but that's the general direction.
